### ISSUE TITLE
Exception while using CLI on Win 10 in conda vartual environment

### ISSUE THREAD

**Issue by allanpk716** [eggplants/get-pixivpy-token#104]
An exception happend while using CLI on Win 10 in conda vartual environment. What should I do to fix it?

```python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\ProgramData\Anaconda3\envs\media_downloader\Scripts\gppt.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'gppt__'
```

**Comment by eggplants** [comment]
I'm not sure about how works on conda. Please share your  `C:\ProgramData\Anaconda3\envs\media_downloader\Scripts\gppt.exe\__main__.py` content.

**Comment by eggplants** [comment]
V4 has been released. Please try and report :bow:
