### ISSUE TITLE
NoSuchElementException

### ISSUE THREAD

**Issue by hiroshihuang** [eggplants/get-pixivpy-token#138]
use CLI with headless browser

```
Traceback (most recent call last):
  File "/home/godz/.local/bin/gppt", line 8, in <module>
    sys.exit(main())
  File "/home/godz/.local/lib/python3.10/site-packages/gppt/main.py", line 135, in main
    args.func(args)
  File "/home/godz/.local/lib/python3.10/site-packages/gppt/main.py", line 60, in func_loginh
    res = g.login(headless=True, username=ns.username, password=ns.password)
  File "/home/godz/.local/lib/python3.10/site-packages/gppt/gppt.py", line 85, in login
    self.__fill_login_form()
  File "/home/godz/.local/lib/python3.10/site-packages/gppt/gppt.py", line 140, in __fill_login_form
    el = self.driver.find_element(By.XPATH, "//input[@autocomplete='username']")
  File "/home/godz/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/home/godz/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)  File "/home/godz/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate
element: {"method":"xpath","selector":"//input[@autocomplete='username']"}
  (Session info: chrome-headless-shell=124.0.6367.91); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x55e553cdccb3 <unknown>
#1 0x55e5539cb4a7 <unknown>
#2 0x55e553a1631d <unknown>
#3 0x55e553a163d1 <unknown>
#4 0x55e553a59734 <unknown>
#5 0x55e553a3843d <unknown>
#6 0x55e553a56be9 <unknown>
#7 0x55e553a381b3 <unknown>
#8 0x55e553a0924a <unknown>
#9 0x55e553a09c1e <unknown>
#10 0x55e553ca0fdb <unknown>
#11 0x55e553ca4f2b <unknown>
#12 0x55e553c8d0f1 <unknown>
#13 0x55e553ca5a92 <unknown>
#14 0x55e553c71faf <unknown>
#15 0x55e553ccbe08 <unknown>
#16 0x55e553ccbfe0 <unknown>
#17 0x55e553cdbe04 <unknown>
#18 0x7f07ec452ac3 <unknown>
```

**Comment by eggplants** [comment]
This error might be fixed in 20cc9c1. Please update to 4.1.0 and run command again.
