### ISSUE TITLE
Consider adding an option to control login timeout please

### ISSUE THREAD

**Issue by RyouMon** [eggplants/get-pixivpy-token#183]
Sometimes you will be asked to provide a verification code when logging into pixiv:
<img width="327" alt="image" src="https://github.com/user-attachments/assets/fb1e1f54-6544-4790-93ac-d64e4849e9e3">

I didn't have enough time to enter the verification code, then program timed out
```
[!]: Chrome browser will be launched. Please login.

DevTools listening on ws://127.0.0.1:12409/devtools/browser/b95a4f62-1da9-442b-b0a8-7eb971be99be
[3536:38060:1130/131155.120:ERROR:ssl_client_socket_impl.cc(878)] handshake failed; returned -1, SSL error code 1, net_error -100
[3536:38060:1130/131155.123:ERROR:ssl_client_socket_impl.cc(878)] handshake failed; returned -1, SSL error code 1, net_error -100
[3536:38060:1130/131155.127:ERROR:ssl_client_socket_impl.cc(878)] handshake failed; returned -1, SSL error code 1, net_error -100
[3536:38060:1130/131155.127:ERROR:ssl_client_socket_impl.cc(878)] handshake failed; returned -1, SSL error code 1, net_error -100
Traceback (most recent call last):
  File "C:\Users\Wen\miniconda3\lib\site-packages\gppt\gppt.py", line 178, in __wait_for_redirect
    WebDriverWait(self.driver, 20).until(EC.url_matches(f"^{REDIRECT_URI}"))
  File "C:\Users\Wen\miniconda3\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Wen\miniconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Wen\miniconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Wen\miniconda3\Scripts\gppt.exe\__main__.py", line 7, in <module>
  File "C:\Users\Wen\miniconda3\lib\site-packages\gppt\main.py", line 135, in main
    args.func(args)
  File "C:\Users\Wen\miniconda3\lib\site-packages\gppt\main.py", line 46, in func_login
    res = g.login(username=ns.username, password=ns.password)
  File "C:\Users\Wen\miniconda3\lib\site-packages\gppt\gppt.py", line 86, in login
    self.__try_login()
  File "C:\Users\Wen\miniconda3\lib\site-packages\gppt\gppt.py", line 152, in __try_login
    self.__wait_for_redirect()
  File "C:\Users\Wen\miniconda3\lib\site-packages\gppt\gppt.py", line 182, in __wait_for_redirect
    raise ValueError(msg) from err
ValueError: Failed to login. Please check your information or proxy. (Maybe restricted by pixiv?)
```

**Comment by RyouMon** [comment]
I temporarily solved this problem by overwriting `GetPixivToken.__wait_for_redirect`
```python
class CustomGetPixivToken(GetPixivToken):
    def _GetPixivToken__wait_for_redirect(self) -> None:
        try:
            WebDriverWait(self.driver, 600).until(EC.url_matches(f"^{REDIRECT_URI}"))
        except TimeoutException as err:
            self.driver.close()
            msg = "Failed to login. Please check your information or proxy. (Maybe restricted by pixiv?)"
            raise ValueError(msg) from err
```

**Comment by xray04** [comment]
Mr. Ryou I have installed the program in PIP, how do I configure the timeout window? I have the same exact issue with CAPTCHA, before solving the CAPTCHA the app closes and I don't know what to do

**Comment by xray04** [comment]
> Mr. Ryou I have installed the program in PIP, how do I configure the timeout window? I have the same exact issue with CAPTCHA, before solving the CAPTCHA the app closes and I don't know what to do

Solved: solution is for PIP installed, for novice windows users like me who have installed the program through pip, please do the following:

1. find the installed directory where this program has been installed on your machine, it is mostly "C:\Program Files\Python313\Lib\site-packages\gppt"

2. add the whole directory to your favorite code editor, then open the py file "gppt".

3. once the file has been opened, scroll to the bottom or until you find the line "WebDriverWait(self.driver, " OR JUST USE CTRL + F then paste the line to immediately go to that line.

4. copy the entire code Above from Mr. Ryou on the same line till the end, then paste it in code editor to replace and modify the timeout window like Mr. Ryou stated.

5. save and re run the program same way: open CMD and enter "gppt login", now the timeout window should have increased.

6. enjoy and expand your art collection of your favorite arts from pixiv (mine is tatsumaki from OPM).

**Comment by eggplants** [comment]
https://pypi.org/project/gppt/4.2.0/
