### ISSUE TITLE
Chrome version problem in docker

### ISSUE THREAD

**Issue by potpotkettle** [eggplants/get-pixivpy-token#42]
I tried the Docker command and it immediately crashed. Is there any workaround?

Environment:
Docker version 20.10.12, build 20.10.12-0ubuntu4

Stacktrace:

```
Traceback (most recent call last):
  File "/usr/local/bin/gppt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/gppt/main.py", line 148, in main
    args.func(args)
  File "/usr/local/lib/python3.10/site-packages/gppt/main.py", line 57, in func_loginh
    res = g.login(headless=True, user=ns.username, pass_=ns.password)
  File "/usr/local/lib/python3.10/site-packages/gppt/_selenium.py", line 65, in login
    self.driver = webdriver.Chrome(
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 277, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 370, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 107
Current browser version is 103.0.5060.114 with binary path /usr/bin/google-chrome
```

**Comment by eggplants** [comment]
Selenium has introduced [Selenium Manager](https://www.selenium.dev/documentation/selenium_manager/), which installs correct selenium-driver automatically. Please try gppt v4.0.0 and report again :bow:

**Comment by Quintasan** [comment]
`docker run --rm -it ghcr.io/eggplants/get-pixivpy-token:4.1 lh -u username-p password`

yields

```
The chromedriver version (114.0.5735.90) detected in PATH at /usr/local/bin/chromedriver might not be compatible with the detected chrome version (124.0.6367.91); currently, chromedriver 124.0.6367.207 is recommended for chrome 124.*, so it is advised to delete the driver in PATH and retry
```

<details>
<summary>Traceback</summary>

```python
Traceback (most recent call last):
  File "/usr/local/bin/gppt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gppt/main.py", line 135, in main
    args.func(args)
  File "/usr/local/lib/python3.12/site-packages/gppt/main.py", line 60, in func_loginh
    res = g.login(headless=True, username=ns.username, password=ns.password)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gppt/gppt.py", line 67, in login
    self.driver = webdriver.Chrome(
                  ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 124.0.6367.91 with binary path /usr/bin/google-chrome
Stacktrace:
#0 0x58b7cecab4e3 <unknown>
#1 0x58b7ce9dac76 <unknown>
#2 0x58b7cea0804a <unknown>
#3 0x58b7cea034a1 <unknown>
#4 0x58b7cea00029 <unknown>
#5 0x58b7cea3eccc <unknown>
#6 0x58b7cea3e47f <unknown>
#7 0x58b7cea35de3 <unknown>
#8 0x58b7cea0b2dd <unknown>
#9 0x58b7cea0c34e <unknown>
#10 0x58b7cec6b3e4 <unknown>
#11 0x58b7cec6f3d7 <unknown>
#12 0x58b7cec79b20 <unknown>
#13 0x58b7cec70023 <unknown>
#14 0x58b7cec3e1aa <unknown>
#15 0x58b7cec946b8 <unknown>
#16 0x58b7cec94847 <unknown>
#17 0x58b7ceca4243 <unknown>
#18 0x7b7b1deb0134 <unknown>
```
</details>

**Comment by eggplants** [comment]
https://pypi.org/project/gppt/4.2.0/
