### ISSUE TITLE
Error with headless mode: `selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable`

### ISSUE THREAD

**Issue by space-nuko** [eggplants/get-pixivpy-token#57]
```
DevTools listening on ws://127.0.0.1:58324/devtools/browser/a6768673-9066-4558-a8a5-c5cd2daaa45c
[0301/170711.413:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is
Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\\AppData\Local\Programs\Python\Python310\Scripts\gppt.exe\__main__.py", line 7, in <module>
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\gppt\main.py", line 148, in main
    args.func(args)
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\gppt\main.py", line 50, in func_logini
    _, res = a.auth()
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\gppt\auth.py", line 22, in auth
    aapi, login_info = self.__auth(cnt)
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\gppt\auth.py", line 47, in __auth
    ref = self.get_refresh_token(stdin_login[0], stdin_login[1])
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\gppt\auth.py", line 58, in get_refresh_token
    res = g.login(headless=True, username=pixiv_id, password=pixiv_pass)
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\gppt\_selenium.py", line 93, in login
    self.__try_login()
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\gppt\_selenium.py", line 166, in __try_login
    el.send_keys(Keys.ENTER)
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 230, in send_keys
    self._execute(
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 403, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: headless chrome=108.0.5359.99)
Stacktrace:
Backtrace:
        (No symbol) [0x00BDF243]
        (No symbol) [0x00B67FD1]
        (No symbol) [0x00A5CF10]
        (No symbol) [0x00A8795E]
        (No symbol) [0x00A870E5]
        (No symbol) [0x00AA858C]
        (No symbol) [0x00A82BFF]
        (No symbol) [0x00AA8804]
        (No symbol) [0x00ABC9EB]
        (No symbol) [0x00AA8386]
        (No symbol) [0x00A8163C]
        (No symbol) [0x00A8269D]
        GetHandleVerifier [0x00E79A22+2655074]
        GetHandleVerifier [0x00E6CA24+2601828]
        GetHandleVerifier [0x00C88C0A+619850]
        GetHandleVerifier [0x00C87830+614768]
        (No symbol) [0x00B705FC]
        (No symbol) [0x00B75968]
        (No symbol) [0x00B75A55]
        (No symbol) [0x00B8051B]
        BaseThreadInitThunk [0x77136709+25]
        RtlGetFullPathName_UEx [0x77BD7D1D+173]
        RtlGetFullPathName_UEx [0x77BD7CEB+123]
```

**Comment by HA-JD** [comment]
Please add your browser（chrome.exe contents） to the environment variable.
