### ISSUE TITLE
There is a login error when reCaptcha occurs

### ISSUE THREAD

**Issue by fatinghenji** [eggplants/get-pixivpy-token#9]
```
[!]: Chrome browser will be launched. Please login.

DevTools listening on ws://127.0.0.1:50733/devtools/browser/11929e54-0deb-463a-a919-b817c72d6e4b
[19148:7992:0401/013412.581:ERROR:device_event_log_impl.cc(214)] [01:34:12.581] USB: usb_service_win.cc:354 Could not get child device's service name: 找不到元素。 (0x490)
[19148:7992:0401/013412.587:ERROR:device_event_log_impl.cc(214)] [01:34:12.588] Bluetooth: bluetooth_adapter_winrt.cc:1075 Getting Default Adapter failed.
Traceback (most recent call last):
  File "f:\python3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "f:\python3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\python3\Scripts\gppt.exe\__main__.py", line 7, in <module>
  File "f:\python3\lib\site-packages\gppt\main.py", line 149, in main
    args.func(args)
  File "f:\python3\lib\site-packages\gppt\main.py", line 44, in func_login
    res = g.login(user=ns.username, pass_=ns.password)
  File "f:\python3\lib\site-packages\gppt\_selenium.py", line 79, in login
    self.__try_login()
  File "f:\python3\lib\site-packages\gppt\_selenium.py", line 163, in __try_login
    raise ValueError("Failed to login")
ValueError: Failed to login
```

**Comment by eggplants** [comment]
Please share your code or executed command.

**Comment by fatinghenji** [comment]
> Please share your code or executed command.

by using `gppt login `

**Comment by eggplants** [comment]
Did you call `reCaptcha` as `Google human verification`?

**Comment by fatinghenji** [comment]
Yes
My English is poor
I'm using a translator to communicate

**Comment by eggplants** [comment]
I try to [prevent](https://github.com/eggplants/get-pixivpy-token/blob/0f0f0c2904b629e53e58ea77de2287ebf4d2b445/gppt/_selenium.py#L139-L143) reCaptcha authentication from occurring, but if it does occur, there is nothing we can do...

**Comment by eggplants** [comment]
I 'll add a process to wait for the authentication to be performed manually in the browser when reCaptcha authentication is requested!

**Comment by fatinghenji** [comment]
> I try to [prevent](https://github.com/eggplants/get-pixivpy-token/blob/0f0f0c2904b629e53e58ea77de2287ebf4d2b445/gppt/_selenium.py#L139-L143) reCaptcha authentication from occurring, but if it does occur, there is nothing we can do...

I think it might be because of network problem in China, I use vpn to login to pixiv. probably many people are using the same node to login at the same time and such behavior triggers Google's reCaptcha. when I change the node this problem goes away.
I will close this issue.

**Comment by fatinghenji** [comment]
> I 'll add a process to wait for the authentication to be performed manually in the browser when reCaptcha authentication is requested!

Looking forward to the release of the new version

**Comment by eggplants** [comment]
Thank you for using my package and report this issue.
